#!/usr/bin/env bash

. "$ELEVATION_BASH_UTILS/core/standard_script.bash"

function main() {
  unset elevation_main_args
  echo "main called with:"
  for x in "$@"; do
    echo "  $x"
  done
  echo "from: $(elevation::script_dir)"
}

elevation::init "$@"

